config/routes.rb
ReloadTransportation::Application.routes.draw do
  resources :trailers

  resources :trucks

  resources :drivers

  get "users/new"

  get "users/create"
  
  get "users/edit"
  
  put "users/update_password"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/drivers"
  get "home/rates"

  match 'dashboard' => 'admin_home#dashboard'
  
  match 'dashboard/new' => 'admin_home#new'
  

  root:to => "home#index"
  

end

app/models/truck.rb
class Truck < ActiveRecord::Base
  attr_accessible :driver_id, :lot_location, :unique_id
  has_one :trailer
  belongs_to :driver
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trucks }
    end
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
    @truck = Truck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @truck }
    end
  end

  # GET /trucks/new
  # GET /trucks/new.json
  def new
    @truck = Truck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @truck }
    end
  end

  # GET /trucks/1/edit
  def edit
    @truck = Truck.find(params[:id])
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(params[:truck])

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render json: @truck, status: :created, location: @truck }
      else
        format.html { render action: "new" }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trucks/1
  # PUT /trucks/1.json
  def update
    @truck = Truck.find(params[:id])

    respond_to do |format|
      if @truck.update_attributes(params[:truck])
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy

    respond_to do |format|
      format.html { redirect_to trucks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= form_for(@truck) do |f| %>
  <% if @truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% @truck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unique_id %><br />
    <%= f.text_field :unique_id %>
  </div>
  <div class="field">
    <%= f.label :driver_id %><br />
    <%= f.text_field :driver_id %>
  </div>
  <div class="field">
    <%= f.label :lot_location %><br />
    <%= f.text_field :lot_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing truck</h1>

<%= render 'form' %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<h1>Listing trucks</h1>

<table>
  <tr>
    <th>Unique</th>
    <th>Driver</th>
    <th>Lot location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trucks.each do |truck| %>
  <tr>
    <td><%= truck.unique_id %></td>
    <td><%= truck.driver_id %></td>
    <td><%= truck.lot_location %></td>
    <td><%= link_to 'Show', truck %></td>
    <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
    <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/new.html.erb
<h1>New truck</h1>

<%= render 'form' %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unique:</b>
  <%= @truck.unique_id %>
</p>

<p>
  <b>Driver:</b>
  <%= @truck.driver_id %>
</p>

<p>
  <b>Lot location:</b>
  <%= @truck.lot_location %>
</p>


<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>