config/routes.rb
ReloadTransportation::Application.routes.draw do
  resources :trailers

  resources :trucks

  resources :drivers

  get "users/new"

  get "users/create"
  
  get "users/edit"
  
  put "users/update_password"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/drivers"
  get "home/rates"

  match 'dashboard' => 'admin_home#dashboard'
  
  match 'dashboard/new' => 'admin_home#new'
  

  root:to => "home#index"
  

end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
  attr_accessible :driver_id, :lot_location, :truck_id, :unique_id
  belongs_to :truck
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  # GET /trailers
  # GET /trailers.json
  def index
    @trailers = Trailer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trailers }
    end
  end

  # GET /trailers/1
  # GET /trailers/1.json
  def show
    @trailer = Trailer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trailer }
    end
  end

  # GET /trailers/new
  # GET /trailers/new.json
  def new
    @trailer = Trailer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trailer }
    end
  end

  # GET /trailers/1/edit
  def edit
    @trailer = Trailer.find(params[:id])
  end

  # POST /trailers
  # POST /trailers.json
  def create
    @trailer = Trailer.new(params[:trailer])

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render json: @trailer, status: :created, location: @trailer }
      else
        format.html { render action: "new" }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trailers/1
  # PUT /trailers/1.json
  def update
    @trailer = Trailer.find(params[:id])

    respond_to do |format|
      if @trailer.update_attributes(params[:trailer])
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    @trailer = Trailer.find(params[:id])
    @trailer.destroy

    respond_to do |format|
      format.html { redirect_to trailers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= form_for(@trailer) do |f| %>
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
      <% @trailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unique_id %><br />
    <%= f.text_field :unique_id %>
  </div>
  <div class="field">
    <%= f.label :driver_id %><br />
    <%= f.text_field :driver_id %>
  </div>
  <div class="field">
    <%= f.label :truck_id %><br />
    <%= f.text_field :truck_id %>
  </div>
  <div class="field">
    <%= f.label :lot_location %><br />
    <%= f.text_field :lot_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing trailer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trailer %> |
<%= link_to 'Back', trailers_path %>

app/views/trailers/index.html.erb
<h1>Listing trailers</h1>

<table>
  <tr>
    <th>Unique</th>
    <th>Driver</th>
    <th>Truck</th>
    <th>Lot location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trailers.each do |trailer| %>
  <tr>
    <td><%= trailer.unique_id %></td>
    <td><%= trailer.driver_id %></td>
    <td><%= trailer.truck_id %></td>
    <td><%= trailer.lot_location %></td>
    <td><%= link_to 'Show', trailer %></td>
    <td><%= link_to 'Edit', edit_trailer_path(trailer) %></td>
    <td><%= link_to 'Destroy', trailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trailer', new_trailer_path %>

app/views/trailers/new.html.erb
<h1>New trailer</h1>

<%= render 'form' %>

<%= link_to 'Back', trailers_path %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unique:</b>
  <%= @trailer.unique_id %>
</p>

<p>
  <b>Driver:</b>
  <%= @trailer.driver_id %>
</p>

<p>
  <b>Truck:</b>
  <%= @trailer.truck_id %>
</p>

<p>
  <b>Lot location:</b>
  <%= @trailer.lot_location %>
</p>


<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>