config/routes.rb
ReloadTransportation::Application.routes.draw do
  resources :trailers

  resources :trucks

  resources :drivers

  get "users/new"

  get "users/create"
  
  get "users/edit"
  
  put "users/update_password"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/drivers"
  get "home/rates"

  match 'dashboard' => 'admin_home#dashboard'
  
  match 'dashboard/new' => 'admin_home#new'
  

  root:to => "home#index"
  

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_one  :truck
  attr_accessible :first_name, :last_name, :phone
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drivers }
    end
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    @driver = Driver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/new
  # GET /drivers/new.json
  def new
    @driver = Driver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/1/edit
  def edit
    @driver = Driver.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(params[:driver])

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render json: @driver, status: :created, location: @driver }
      else
        format.html { render action: "new" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drivers/1
  # PUT /drivers/1.json
  def update
    @driver = Driver.find(params[:id])

    respond_to do |format|
      if @driver.update_attributes(params[:driver])
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<h1>Listing drivers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drivers.each do |driver| %>
  <tr>
    <td><%= driver.first_name %></td>
    <td><%= driver.last_name %></td>
    <td><%= driver.phone %></td>
    <td><%= link_to 'Show', driver %></td>
    <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
    <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @driver.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @driver.last_name %>
</p>

<p>
  <b>Phone:</b>
  <%= @driver.phone %>
</p>


<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>