config/routes.rb
ReloadTransportation::Application.routes.draw do
  resources :trailers

  resources :trucks

  resources :drivers

  get "users/new"

  get "users/create"
  
  get "users/edit"
  
  put "users/update_password"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/drivers"
  get "home/rates"

  match 'dashboard' => 'admin_home#dashboard'
  
  match 'dashboard/new' => 'admin_home#new'
  

  root:to => "home#index"
  

end

app/views/layouts/_footer.html.erb
        <!-- start: Footer Menu -->
	<div id="footer-menu" class="hidden-tablet hidden-phone">

		<!-- start: Container -->
		<div class="container">
			
			<!-- start: Row -->
			<div class="row">

				<!-- start: Footer Menu Logo -->
				<div class="span2">
					<div id="footer-menu-logo">
						<div id="logo-chart"></div><a class="brand" href="#">Reload<span>Transportation</span></a>
					</div>
				</div>
				<!-- end: Footer Menu Logo -->

				<!-- start: Footer Menu Links-->
				<div class="span9">
					
					<div id="footer-menu-links">

						<ul id="footer-nav">

							<li><a href="index3.html">Home</a></li>
							
							<li><a href="about.html">About</a></li>

							<li><a href="admin.html">Employees</a></li>

							<li><a href="drivers.html">Drivers</a></li>

							<li><a href="contact.html">Contact Us</a></li>
							
							<li><a href="contact.html">Rates</a></li>
							
							
						</ul>

					</div>
					
				</div>
				<!-- end: Footer Menu Links-->

				<!-- start: Footer Menu Back To Top -->
				<div class="span1">
						
					<div id="footer-menu-back-to-top">
						<a href="#"></a>
					</div>
				
				</div>
				<!-- end: Footer Menu Back To Top -->
			
			</div>
			<!-- end: Row -->
			
		</div>
		<!-- end: Container  -->	

	</div>	
	<!-- end: Footer Menu -->

	<!-- start: Footer -->
	<div id="footer">
		
		<!-- start: Container -->
		<div class="container">
			
			<!-- start: Row -->
			<div class="row">

				<!-- start: About -->
				<div class="span3">
					
					<h3>About Us</h3>
					<p>
					Welcome to Reload Transportation Services LLC dba Cowan Systems LLC. We are a Chicago – based full service intermodal logistics company with offices in Chicago, St. Louis and Kansas City, Memphis, and Nashville. We are proud to combine a young and energetic team along with knowledgeable veterans in the industry with over 30 years of experience.
					</p>
						
				</div>
				<!-- end: About -->

				

				<div class="span3 offset4">
				
					<!-- start: Follow Us -->
					<h3>Follow Us!</h3>
					<ul class="social-grid">
						<li>
							<div class="social-item">				
								<div class="social-info-wrap">
									<div class="social-info">
										<div class="social-info-front social-twitter">
											<a href="https://twitter.com/ReloadTrans"></a>
										</div>
										<div class="social-info-back social-twitter-hover">
											<a href="https://twitter.com/ReloadTrans"></a>
										</div>	
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="social-item">				
								<div class="social-info-wrap">
									<div class="social-info">
										<div class="social-info-front social-facebook">
											<a href="https://www.facebook.com/pages/Reload-Transportation/114807175221694?fref=ts"></a>
										</div>
										<div class="social-info-back social-facebook-hover">
											<a href="https://www.facebook.com/pages/Reload-Transportation/114807175221694?fref=ts"></a>
										</div>
									</div>
								</div>
							</div>
						</li>
						
					</ul>
					<!-- end: Follow Us -->
				
					<!-- Begin MailChimp Signup Form -->
<link href="http://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="http://10secondlabs.us6.list-manage.com/subscribe/post?u=b7d1acaefd7d19247c6874838&amp;id=73ce1873af" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<label for="mce-EMAIL">Subscribe to our mailing list</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
	<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->



				
				</div>
				
			</div>
			<!-- end: Row -->	
			
		</div>
		<!-- end: Container  -->

	</div>
	<!-- end: Footer -->

	<!-- start: Copyright -->
	<div id="copyright">
	
		<!-- start: Container -->
		<div class="container">
		
			<div class="span12">
				<p>
					&copy; 2012, <a href="http://www.10secondlabs.com">10 Second Labs</a>. Designed by <a href="http://www.vincentaguirre.com">Vincent M. Aguirre</a> 
				</p>
			</div>
	
		</div>
		<!-- end: Container  -->
		
	</div>	
	<!-- end: Copyright -->

app/views/layouts/_header.html.erb
<header>
	
	<!--start: Container -->
	<div class="container">
		
		<!--start: Navbar -->
		<div class="navbar navbar-inverse">
    		<div class="navbar-inner">
          		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>
          		</a>
				<a class="brand" href="index4.html"></i>Reload<span>Transportation</span></a>
          		<div class="nav-collapse collapse">
            		<ul class="nav">
                			<li><%= link_to "Home", home_index_path %></li>
							<li><%= link_to "About", home_about_path %></li>

                			
						<li class="dropdown">
                			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Employees<b class="caret"></b></a>
                			<ul class="dropdown-menu">
								<li><a href="admin.html">Administration</a></li>
                  				<li><a href="chicago.html">Chicago</a></li>
								<li><a href="stl.html">St Louis</a></li>
								<li><a href="kc.html">Kansas City</a></li>
								<li><a href="memphis.html">Memphis</a></li>
								<li><a href="nashville.html">Nashville</a></li>
                			</ul>
              			</li>
						<li><%= link_to "Drivers", home_drivers_path %></li>					
						<li><%= link_to "Contact Us", home_contact_path %></li>
						<li><%= link_to "Rates", home_rates_path %></li>
						<%if current_user%>
						<li><%= link_to "Logout", destroy_user_session_path , method: :delete%></li>
						<%end%>
            		</ul>
          		</div>
        	</div>
      	</div>
		<!--end: Navbar -->
		
	</div>
	<!--end: Container-->			
		
</header>
<!--end: Header-->

app/views/layouts/_scripts.html.erb
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "bootstrap" %>
<%= javascript_include_tag "isotope" %>
<%= javascript_include_tag "flexslider" %>
<%= javascript_include_tag "carousel" %>
<%= javascript_include_tag "jquery.cslider" %>
<%= javascript_include_tag "slider" %>
<%= javascript_include_tag "fancybox" %>
<%= javascript_include_tag "custom" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Reload Transportation</title> 
	<meta name="description" content="Reload Transportation"/>
	<meta name="keywords" content="Trucking, Transportation, Reload, Intermodal, Logistics, Chicago, Kansas City, St Louis, Memphis" />
	<meta name="author" content="Vincent M. Aguirre from 10 Second Labs"/>
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: Facebook Open Graph -->
	<meta property="og:title" content=""/>
	<meta property="og:description" content=""/>
	<meta property="og:type" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:image" content=""/>
	
	
	<!-- end: Facebook Open Graph -->

	<%= stylesheet_link_tag  "application", :media => "all" %>
	<%= stylesheet_link_tag  "bootstrap", :media => "all" %>
	<%= stylesheet_link_tag  "bootstrap-responsive", :media => "all" %>
	<%= stylesheet_link_tag  "social-icons", :media => "all" %>
	<%= stylesheet_link_tag  "fancybox", :media => "all" %>
	<%= stylesheet_link_tag  "hover", :media => "all" %>
	<%= stylesheet_link_tag  "icons", :media => "all" %>
	<%= stylesheet_link_tag  "icons-color", :media => "all" %>
	<%= stylesheet_link_tag  "parallax-slider", :media => "all" %>
	<%= stylesheet_link_tag  "parallax-slider2", :media => "all" %>
	<%= stylesheet_link_tag  "style", :media => "all" %>
	<%= stylesheet_link_tag  "styleie9", :media => "all" %>
  

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic">

  
</head>
<body>
 <!--render header -->
<%= render 'layouts/header' %>


<%= yield %>

<!--render footer-->
<%= render 'layouts/footer' %>
<!-- render scripts-->
<%= render 'layouts/scripts'%>


</body>
</html>